name: Solsta Deployment Action
description: Deploy a release
inputs:
  working_directory:
    description: Relative path to folder containing deployable artifacts
    required: false
    default: ""
  console_version:
    description: Version of Solsta Console Tools to use
    required: true
    default: "6.1.1.12"
  target_product:
    description: Target product for deployment (case-sensitive)
    required: true
  target_environment:
    description: Target environment for deployment (case-sensitive)
    required: false
  target_repository:
    description: Target repository for deployment (case-sensitive)
    required: false

outputs:
  result:
    description: The state of the action, if processes completed successfully

runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.working_directory }}
    - ${{ inputs.console_version }}
    - ${{ inputs.target_product }}
    - ${{ inputs.target_environment }}
    - ${{ inputs.target_repository }}
  env:
    SNXD_CLIENT_ID:  ${{ secrets.SNXD_CLIENT_ID }}
    SNXD_CLIENT_SECRET:  ${{ secrets.SNXD_CLIENT_SECRET }}
branding:
  icon: "download-cloud"
  color: "yellow"
